### ISSUE TITLE
Some things I'd like:

### ISSUE THREAD

**Issue by aileennicolas** [watsonmartin/aileens-clock#2]
@watsonmartin 

Clock layout:
-------------------
[no title]
clock (larger font)

timer (larger font)
[timer type - work, or if zero, read break]
pomo #1, 2 3, 4 etc. (in smaller font)
---------------------------

Some other things I've been thinking of that aren't the clock:
current mood:
[     ] (something I can edit)

chat interactions like
!pet q - give q pets for the viewers
!snack q - give q snacks from the viewers

also like...
little rolling headers to announce that I'm ending the stream after a timer or that I'm going on break after this timer, idk, a rolling header that I can edit??

**Comment by watsonmartin** [comment]
Closing as this is now out of date and many of the suggestions have been addressed.
